Read and write of scc files in C++
DavidLapous/multipers pull request #28
Opened 2024-10-14 13:54 UTC by hschreiber

2024-10-15 07:19 UTC, DavidLapous requested changes
LGTM, apart from an issue with `strip_comments=False` (no issues if `True`)
```py
s.write_to_scc_file("truc.scc", strip_comments=False)
s = mp.Slicer()
s._build_from_scc_file("truc.scc")
```
which (up to adding an `except +` in the `slicer.pxd` file) throws with
```
Wrong format. The number of cells in each dimension is wrong.
```
I guess the reader function doesn't ignore the comments.

2024-10-15 13:21 UTC, hschreiber commented
> LGTM, apart from an issue with `strip_comments=False` (no issues if `True`)
> 
> ```python
> s.write_to_scc_file("truc.scc", strip_comments=False)
> s = mp.Slicer()
> s._build_from_scc_file("truc.scc")
> ```
> 
> which (up to adding an `except +` in the `slicer.pxd` file) throws with
> 
> ```
> Wrong format. The number of cells in each dimension is wrong.
> ```
> 
> I guess the reader function doesn't ignore the comments.

The comments where ignored, but the format check was placed to soon. And after adding the possibility of shifting for the dimensions, the check became also wrong and I forgot to remove it.
It should work now.

2024-10-15 13:36 UTC, DavidLapous approved these changes

2024-10-15 13:36 UTC, DavidLapous commented on multipers/slicer.pxd.tp
>        void write_to_scc_file(const string&, int, int, bool, bool, bool, bool)
`nogil`?

2024-10-16 18:23 UTC, DavidLapous commented
interface should be ok now

2024-10-16 18:32 UTC, DavidLapous commented
LGTM. I will fix test later

2024-10-16 18:32 UTC, merged